#!/usr/bin/env python3
"""Work out the page order for printing, and write build/impose.tex.

THE PROBLEM
-----------
The book's pages are 3.5in x 5.5in. Four of them fit on a sheet of US
Letter, two across and two down. We want to print double-sided, cut the
sheet into four rectangles with scissors, stack the rectangles, and sew
along the spine edge -- so each rectangle has to come off the press with
consecutive pages back to back, and the rectangles have to stack in order.

THE ARRANGEMENT
---------------
Sheet k carries pages 8k+1 .. 8k+8.

  Front of sheet            Back of sheet
  +--------+--------+       +--------+--------+
  |   1    |   3    |       |   4    |   2    |
  +--------+--------+       +--------+--------+
  |   5    |   7    |       |   8    |   6    |
  +--------+--------+       +--------+--------+

A long-edge duplex flip mirrors a portrait sheet left-to-right, so the
back of the top-left rectangle is the top-RIGHT slot of the back side.
Putting page 2 there is what makes page 1 and page 2 land on the two faces
of the same piece of paper.

Cut into four, keep them in reading order (top-left, top-right, bottom-left,
bottom-right), stack all sheets, sew the left edge.

`--scheme saddle` instead nests each group of 8 pages into a folded
signature, for anyone who would rather sew through the fold.
"""

import argparse
import os

PER_SHEET = 8

FRONT_SLOTS = [0, 2, 4, 6]   # which of the 8 pages goes in each front slot
BACK_SLOTS = [3, 1, 7, 5]    # ... and each back slot, already mirrored


def flat_order(n_pages):
    """Page numbers in the order pdfpages should place them, 1-indexed."""
    order = []
    n_sheets = (n_pages + PER_SHEET - 1) // PER_SHEET
    for sheet in range(n_sheets):
        base = sheet * PER_SHEET
        for slots in (FRONT_SLOTS, BACK_SLOTS):
            for s in slots:
                page = base + s + 1
                order.append(page if page <= n_pages else None)
    return order


def saddle_order(n_pages):
    """Folded-signature order: 8 pages per sheet, folded twice."""
    order = []
    n_sheets = (n_pages + PER_SHEET - 1) // PER_SHEET
    for sheet in range(n_sheets):
        base = sheet * PER_SHEET
        # Outer fold pairs first and last, and so inward.
        front = [base + 8, base + 1, base + 5, base + 4]
        back = [base + 2, base + 7, base + 3, base + 6]
        for group in (front, back):
            for page in group:
                order.append(page if page <= n_pages else None)
    return order


def verify_flat(n_pages):
    """Check every rectangle really carries consecutive pages."""
    order = flat_order(n_pages)
    problems = []
    for sheet in range(len(order) // PER_SHEET):
        front = order[sheet * 8: sheet * 8 + 4]
        back = order[sheet * 8 + 4: sheet * 8 + 8]
        # Slot i on the front is backed by the mirrored slot on the back:
        # 0<->1 and 2<->3 swap within each row.
        mirror = {0: 1, 1: 0, 2: 3, 3: 2}
        for i in range(4):
            f, b = front[i], back[mirror[i]]
            if f is None or b is None:
                continue
            if b != f + 1:
                problems.append(
                    "sheet %d slot %d: front page %s backed by %s"
                    % (sheet + 1, i, f, b))
    return problems


# Two paper sizes, same four pages. A 3.5in by 5.5in page is 88.9 by
# 139.7mm, so 2x2 is 177.8 by 279.4mm. On US Letter that leaves 3/4in of
# waste at each side and nothing top or bottom -- two pages down is 11in
# exactly. On A4 it leaves 16.1mm at each side and 8.8mm top and bottom,
# so A4 needs three horizontal cuts where Letter needs one.
PAPERS = {
    "letter": {
        "geometry": "letterpaper",
        "label": "US Letter",
        "unit": "in",
        "vcuts": [0.75, 4.25, 7.75],
        "hcuts": [5.5],
    },
    "a4": {
        "geometry": "a4paper",
        "label": "A4",
        "unit": "mm",
        "vcuts": [16.1, 105.0, 193.9],
        "hcuts": [8.8, 148.5, 288.2],
    },
}


def cut_marks(paper):
    """The tikz for one paper's cut lines, edge to edge.

    Run full bleed rather than stopping at the trim: a line that carries
    on into the waste is a line scissors can be lined up against before
    they reach the paper, which is the whole point of printing it.
    """
    spec = PAPERS[paper]
    u = spec["unit"]
    out = []
    for x in spec["vcuts"]:
        out.append(
            r"    \draw[cutline, line width=0.3pt] "
            r"([xshift=%g%s]current page.north west) -- "
            r"([xshift=%g%s]current page.south west);" % (x, u, x, u))
    for y in spec["hcuts"]:
        out.append(
            r"    \draw[cutline, line width=0.3pt] "
            r"([yshift=-%g%s]current page.north west) -- "
            r"([yshift=-%g%s]current page.north east);" % (y, u, y, u))
    return "\n".join(out)


TEMPLATE = r"""%% Generated by tools/impose.py -- do not edit.
%%
%% %(description)s
%%
%% %(n_pages)d book pages -> %(n_sheets)d sheets of %(paper_label)s, printed
%% double-sided, flipped on the LONG edge.
\documentclass{article}
\usepackage[%(paper_geometry)s,margin=0pt]{geometry}
\usepackage{pdfpages}
\usepackage{tikz}
\usepackage{xcolor}
\pagestyle{empty}

%% Drawn here rather than with pdfpages' own frame option, which is a
%% black hairline with no way to soften it. Matched to the book's hairline
%% gray: a third of a point at 3.95:1, which a laser prints faithfully and
%% which is still light enough that a remnant of it after an imperfect cut
%% does not read as a border. The first attempt at 9A9A9A looked right on
%% screen and needed good light to follow on paper.
\definecolor{cutline}{HTML}{7E7E7E}
\newcommand{\cutlines}{%%
  \begin{tikzpicture}[remember picture, overlay]
%(cut_marks)s
  \end{tikzpicture}}
\AddToHook{shipout/background}{\cutlines}

\begin{document}
\includepdf[
  pages={%(pages)s},
  nup=2x2,
  noautoscale=true,
  delta=0pt 0pt,
  frame=%(frame)s,
  turn=false,
]{%(source)s}
\end{document}
"""

DESCRIPTIONS = {
    "flat": "Cut into quarters, stack in order, sew along the spine edge.",
    "saddle": "Fold twice, nest, sew through the fold.",
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pages", type=int, required=True,
                    help="how many pages the book PDF has")
    ap.add_argument("--source", default="voicings-screen.pdf")
    ap.add_argument("--scheme", choices=["flat", "saddle"], default="flat")
    ap.add_argument("--crop-marks", action="store_true",
                    help="draw a frame on each rectangle to cut along")
    ap.add_argument("--out", default="build/impose.tex")
    args = ap.parse_args()

    order = (flat_order if args.scheme == "flat" else saddle_order)(args.pages)

    if args.scheme == "flat":
        problems = verify_flat(args.pages)
        if problems:
            for p in problems:
                print("IMPOSITION ERROR:", p)
            return 1

    pages = ",".join("{}" if p is None else str(p) for p in order)
    text = TEMPLATE % dict(
        description=DESCRIPTIONS[args.scheme],
        n_pages=args.pages,
        n_sheets=len(order) // PER_SHEET,
        pages=pages,
        source=args.source,
        frame="true" if args.crop_marks else "false",
    )
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write(text)
    print("wrote %s: %d pages on %d sheets (%s)"
          % (args.out, args.pages, len(order) // PER_SHEET, args.scheme))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
