#!/usr/bin/env python3
"""Generate data/voicings/piano.yaml from data/piano-shapes.yaml.

The keyboard pages are one idiom transposed twelve times, so writing them
out by hand would be 350 chances to make a typo. The shapes live in
data/piano-shapes.yaml; this expands them into every key, spelling each
note the way the harmony calls for -- B-double-flat where the chord wants
a minor third above G-flat, not A.

Run `make piano` after editing the shapes.
"""

import os
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import theory  # noqa: E402

# The keys in the order the book prints them, spelled as a worship chart
# spells them: flats everywhere except the sharp keys a guitar lives in.
KEYS = ["C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B"]


# Keys a guitarist and a pianist both write with sharps. Everything else
# takes flats.
SHARP_KEYS = {"G", "D", "A", "E", "B"}


def voice(root, intervals, quality=None, key=None):
    """A shape in one key, as a note list low to high.

    Notes are named by the key you actually put a finger on: A, not
    B-double-flat. Strict spelling is right about the harmony -- the minor
    third of G-flat minor really is B-double-flat -- but nobody hunts a
    keyboard for one, and a four-character name in a two-column table
    costs room the page does not have.

    Flat keys are spelled with flats and sharp keys with sharps, so a
    voicing never mixes the two arbitrarily.
    """
    flat = (key or root) not in SHARP_KEYS
    base = theory.parse_note(root)
    return "-".join(theory.spell(base + i, flat) for i in intervals)


def build(shapes_path="data/piano-shapes.yaml"):
    spec = yaml.safe_load(open(shapes_path))
    doc = {
        "instrument": "piano",
        "source": spec.get("source", "generated"),
        "keys": [],
    }
    for key in KEYS:
        chords = []
        for quality, shape in spec["shapes"].items():
            symbol = key + quality.replace("o", "°")
            # One voicing per chord: close root position, which answers
            # "what notes are in this chord" -- the question the page is
            # open to. The open worship voicings stay in piano-shapes.yaml
            # rather than crowding the page beside them.
            entry = {"chord": symbol,
                     "frets": [voice(key, shape["close"], quality, key)]}
            if shape.get("note"):
                entry["note"] = shape["note"]
            if shape.get("star"):
                entry["star"] = True
            chords.append(entry)
        for slash in spec["slashes"]:
            flat = key not in SHARP_KEYS
            bass = theory.spell(theory.parse_note(key) + slash["bass"], flat)
            symbol = "%s%s/%s" % (key, slash["quality"], bass)
            chords.append({
                "chord": symbol,
                "frets": [voice(key,
                                slash.get("close", slash["open"]),
                                slash["quality"], key)],
                "note": slash.get("note", ""),
            })
        doc["keys"].append({"key": key, "chords": chords})
    return doc


def main():
    doc = build()
    out = "data/voicings/piano.yaml"
    with open(out, "w") as fh:
        fh.write("# Generated by tools/piano.py from data/piano-shapes.yaml.\n"
                 "# Do not edit by hand -- edit the shapes and rerun.\n"
                 "# Voicings are note names, low to high.\n")
        yaml.safe_dump(doc, fh, sort_keys=False, allow_unicode=True, width=100)
    n = sum(len(k["chords"]) for k in doc["keys"])
    print("wrote %s: %d chords across %d keys" % (out, n, len(doc["keys"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
