#!/usr/bin/env python3
"""Work out where to spike the banjo's 5th string for each key.

The 5th string is a drone: it rings open every time it is brushed, so it
has to be a note that belongs to the tonic chord or it fights the tune.
It is not fretted -- it is caught under a railroad spike (or a 5th-string
capo) at a chosen fret, which raises it and leaves it raised.

The string starts at the 5th fret, so a spike at fret N raises it by N-5
semitones from its open g. Most necks carry spikes at 7, 9 and 10; 8 and
12 are common additions. Anything else means moving the capo.

Preference order for the drone: the root of the key, then the fifth, then
the third. The root is the safest drone; the fifth is the sweetest under a
I-IV-V; the third colors the chord and is the one to avoid if the tune
moves between major and minor.
"""

import os
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import theory  # noqa: E402

OPEN_FRET = 5           # where the 5th string starts
OPEN_PC = theory.NOTE_TO_PC["G"]
# What this neck actually has. Everything else means retuning the string.
AVAILABLE = [5, 7, 9]   # 5 is the string's own nut: open g

KEYS = ["C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B"]


def pitch_at(fret, detune=0):
    """What the 5th string sounds, spiked here and tuned by `detune`."""
    return (OPEN_PC + fret - OPEN_FRET + detune) % 12


def options(root_pc, quality):
    """Ranked drone choices for one key.

    Only three spikes exist on this neck, so for five of the twelve keys no
    chord tone is reachable at all. Rather than send the player to a fret
    that isn't there, those keys get told to move the string itself: a
    half step off an existing spike is one peg turn, and it is what anyone
    does in practice.
    """
    third = 3 if quality == "minor" else 4
    degrees = [(0, "root"), (7, "fifth"), (third, "third")]
    out = []
    for interval, label in degrees:
        want = (root_pc + interval) % 12
        for fret in AVAILABLE:
            for detune in (0, -1, 1):
                if pitch_at(fret, detune) != want:
                    continue
                out.append({
                    "fret": fret,
                    "note": theory.spell(want),
                    "degree": label,
                    "detune": detune,
                    "open": fret == OPEN_FRET and detune == 0,
                })
    # A spike you can just drop into beats one you have to retune for; the
    # root beats the fifth beats the third.
    # No retune at all is best; then slackening rather than tightening,
    # which is kinder to a string you are about to put back.
    out.sort(key=lambda o: (o["detune"] != 0, o["detune"] > 0, not o["open"]))
    return out


def build():
    rows = []
    for key in KEYS:
        root = theory.NOTE_TO_PC[key]
        row = {"key": key}
        for quality in ("major", "minor"):
            opts = options(root, quality)
            best = opts[0]
            row[quality] = {
                "fret": best["fret"],
                "note": best["note"],
                "degree": best["degree"],
                "open": best["open"],
                "detune": best["detune"],
                "alternates": [
                    {"fret": o["fret"], "note": o["note"],
                     "degree": o["degree"], "detune": o["detune"]}
                    for o in opts[1:3]
                ],
            }
        rows.append(row)
    return rows


if __name__ == "__main__":
    data = {
        "note": "Spike the 5th string at this fret. 'Open' means leave it "
                "alone -- the open g is already a chord tone. A detune of "
                "-1 or +1 means no spike on this neck reaches a chord tone, "
                "so tune the string itself a half step from the nearest "
                "one.",
        "open_fret": OPEN_FRET,
        "spikes": AVAILABLE,
        "keys": build(),
    }
    out = os.path.join("data", "banjo-spikes.yaml")
    with open(out, "w") as fh:
        fh.write("# Generated by tools/spikes.py -- do not edit by hand.\n")
        yaml.safe_dump(data, fh, sort_keys=False, allow_unicode=True)
    print("wrote", out)
    for r in data["keys"]:
        M, m = r["major"], r["minor"]
        def f(d):
            base = "open g" if d["fret"] == OPEN_FRET else "fret %d" % d["fret"]
            if d["detune"]:
                base += ", tune %s a half step" % ("down" if d["detune"] < 0
                                                  else "up")
            return base
        print("  %-2s  major: %-30s -> %-2s (%s)" %
              (r["key"], f(M), M["note"], M["degree"]))
        print("      minor: %-30s -> %-2s (%s)" %
              (f(m), m["note"], m["degree"]))
