#!/usr/bin/env python3
"""Work out where to spike the banjo's 5th string for each key.

The 5th string is a drone: it rings open every time it is brushed, so it
has to be a note that belongs to the tonic chord or it fights the tune.
It is not fretted -- it is caught under a railroad spike (or a 5th-string
capo) at a chosen fret, which raises it and leaves it raised.

The string starts at the 5th fret, so a spike at fret N raises it by N-5
semitones from its open g. Most necks carry spikes at 7, 9 and 10; 8 and
12 are common additions. Anything else means moving the capo.

Preference order for the drone: the root of the key, then the fifth, then
the third. The root is the safest drone; the fifth is the sweetest under a
I-IV-V; the third colours the chord and is the one to avoid if the tune
moves between major and minor.
"""

import os
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import theory  # noqa: E402

OPEN_FRET = 5           # where the 5th string starts
OPEN_PC = theory.NOTE_TO_PC["G"]
COMMON = {7, 9, 10}     # spikes on a typical neck
ALSO_SEEN = {8, 12}     # often added
SEARCH = range(5, 13)   # open g up to the octave

KEYS = ["C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B"]


def options(root_pc, quality):
    """Ranked drone choices for one key."""
    third = 3 if quality == "minor" else 4
    degrees = [(0, "root"), (7, "fifth"), (third, "third")]
    out = []
    for interval, label in degrees:
        want = (root_pc + interval) % 12
        for fret in SEARCH:
            if (OPEN_PC + fret - OPEN_FRET) % 12 == want:
                out.append({
                    "fret": fret,
                    "note": theory.spell(want),
                    "degree": label,
                    "common": fret in COMMON or fret == OPEN_FRET,
                    "open": fret == OPEN_FRET,
                })
    # A spike the neck already has beats one it does not.
    out.sort(key=lambda o: (not o["common"], not o["open"]))
    return out


def build():
    rows = []
    for key in KEYS:
        root = theory.NOTE_TO_PC[key]
        row = {"key": key}
        for quality in ("major", "minor"):
            opts = options(root, quality)
            best = opts[0]
            row[quality] = {
                "fret": best["fret"],
                "note": best["note"],
                "degree": best["degree"],
                "open": best["open"],
                "common": best["common"],
                "alternates": [
                    {"fret": o["fret"], "note": o["note"], "degree": o["degree"]}
                    for o in opts[1:3]
                ],
            }
        rows.append(row)
    return rows


if __name__ == "__main__":
    data = {
        "note": "Spike the 5th string at this fret. 'Open' means leave it "
                "alone -- the open g is already a chord tone.",
        "open_fret": OPEN_FRET,
        "common_spikes": sorted(COMMON),
        "keys": build(),
    }
    out = os.path.join("data", "banjo-spikes.yaml")
    with open(out, "w") as fh:
        fh.write("# Generated by tools/spikes.py -- do not edit by hand.\n")
        yaml.safe_dump(data, fh, sort_keys=False, allow_unicode=True)
    print("wrote", out)
    for r in data["keys"]:
        M, m = r["major"], r["minor"]
        f = lambda d: ("open g" if d["open"] else "fret %d" % d["fret"])
        print("  %-2s  major: %-8s -> %-2s (%s)   minor: %-8s -> %-2s (%s)"
              % (r["key"], f(M), M["note"], M["degree"],
                 f(m), m["note"], m["degree"]))
